---
include:

  - board: nice_nano//zmk
    shield: totem_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: totem_dongle

  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left

  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right
  # - board: xiao_ble//zmk
  #   shield: settings_reset
